[package]
name = "cli-image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
comfy-table = "6.1.0"
clap = { version = "3.1.8", features = ["derive"] }
indicatif = "0.16.2"